project/views/auth.py
from logging import getLogger

from flask import Blueprint, redirect, render_template, request, url_for
from flask_login import (
    current_user,
    login_user,
    logout_user,
    login_required,
)
from werkzeug.exceptions import BadRequest, InternalServerError

from models import User
from models.db import Session


logger = getLogger(__name__)

auth = Blueprint("auth", __name__)


@auth.route("/register/", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for("home"))

    if request.method == "GET":
        return render_template("auth/register.html", user=current_user)

    username = request.form.get("username")
    password = request.form.get("password")
    if not (username and len(username) >= 3 and password and len(password) >= 4):
        return render_template(
            "auth/register.html",
            error_text="Username has to be at least 3 symbols and pass min 5",
            user=current_user,
        )
    if Session.query(User).filter_by(username=username).count():
        return render_template(
            "auth/register.html",
            error_text=f"Username {username!r} already exists!",
            user=current_user,
        )

    user = User(username, password)
    Session.add(user)

    try:
        Session.commit()
    except Exception as e:
        logger.exception("Error creating user!")
        raise InternalServerError(f"Could not create new user! Error: {e}")

    login_user(user)
    return redirect(url_for("home"))


@auth.route("/login/", methods=["GET", "POST"], endpoint="login")
def login():
    if current_user.is_authenticated:
        return redirect(url_for("home"))

    if request.method == "GET":
        return render_template("auth/login.html", user=current_user)

    username = request.form.get("username")
    password = request.form.get("password")

    user = Session.query(User).filter_by(username=username).one_or_none()

    if not user:
        return render_template("auth/login.html", error_text="User not found")

    if user.password != User.hash_password(password):
        return render_template(
            "auth/login.html",
            error_text="Invalid username or password!",
            user=current_user,
        )

    login_user(user)
    return redirect(url_for("home"))


@auth.route("/logout/", endpoint="logout")
def logout():
    logout_user()
    return redirect(url_for("home"))


@auth.route("/profile/", endpoint="profile")
@login_required
def profile():
    return render_template("auth/profile.html", user=current_user)

project/views/post.py
from logging import getLogger

from flask import Blueprint, redirect, render_template, request, url_for
from flask_login import (
    current_user,
    login_user,
    logout_user,
    login_required,
)
from werkzeug.exceptions import BadRequest, InternalServerError

from models import Post
from models.db import Session


logger = getLogger(__name__)

post = Blueprint("post", __name__)


def validate_user_credentials(username: str, password: str):
    if not (username and len(username) >= 3 and password and len(password) >= 4):
        raise BadRequest("Username has to be at least 3 symbols and pass min 4")


def get_username_and_password_from_form(form: dict):
    username = form.get("username")
    password = form.get("password")
    validate_user_credentials(username, password)
    return username, password


@post.route("/add/", methods=["GET", "POST"], endpoint="add_post")
@login_required
def add_post():

    if request.method == "GET":
        return render_template("post/add_post.html", user=current_user)

    title = request.form["title"]
    text = request.form["text"]
    if not title:
        return render_template(
            "post/add_post.html", error_text="Title can't be empty", user=current_user
        )
    if not text:
        return render_template(
            "post/add_post.html", error_text="Text can't be empty", user=current_user
        )
    new_post = Post(title, text, current_user.id)
    Session.add(new_post)
    try:
        Session.commit()
    except Exception as e:
        logger.exception("Error creating post!")
        raise InternalServerError(f"Could not create new post! Error: {e}")

    return redirect(url_for("home"))


@post.route("/<int:id>/")
@login_required
def post_view(id):
    post = Session.query(Post).filter_by(id=id).one_or_none()
    if post:
        return render_template("post/post.html", user=current_user, post=post)
    else:
        return redirect(url_for("home"))

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
        integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <title>
        {% block title %}{% endblock %}
    </title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-fixed-top" style="background:#FFFAF0;">
        <div class="container">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href=" {{ url_for('home') }}">Posts</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href=" {{ url_for('contacts') }}">Contacts</a>
                </li>
            </ul>
            <ul class="navbar-right">
                {% if user.is_authenticated %}
                {% if user.username == "admin" %}
                <a href=" {{ url_for('post.add_post') }}" class="btn btn-outline-success btn-sm">Add Post</a>
                {% endif%}
                <a href=" {{ url_for('auth.profile') }}" class="btn btn-outline-primary btn-sm">Profile</a>
                <a href=" {{ url_for('auth.logout') }}" class="btn btn-outline-dark btn-sm">Logout</a>
                {% else %}
                <a href=" {{ url_for('auth.login') }}" class="btn btn-outline-primary btn-sm">Login</a>
                <a href=" {{ url_for('auth.register') }}" class="btn btn-outline-success btn-sm">Register</a>
                {% endif %}
            </ul>
        </div>
    </nav>
    <div class=" container">
        {% block body %}{% endblock %}
    </div>

</body>

</html>